version: '3'

services:
  newsbot:
    container_name: newsbot
    build:
      dockerfile: Dockerfile
      context: .
    restart: unless-stopped
    volumes:
      - ./database:/usr/src/app/database
    env_file:
      - .env